name: ignite_cli
description: Ignite your projects with flame; a CLI scaffolding tool to create and setup your Flame projects
version: 0.2.0
repository: https://github.com/flame-engine/ignite-cli

# Add the bin/ignite.dart script to the scripts pub installs
executables:
  ignite:

environment:
  sdk: '>=2.9.3 <3.0.0'

dependencies:
  yaml: ^2.2.1
  args: ^1.6.0
  completion: ^0.2.3
  process_run: ^0.11.2+8
  prompts: ^1.3.1
  io: ^0.3.2
  path: ^1.8.0

dev_dependencies:
  dart_code_metrics: ^2.4.0
  pedantic: ^1.9.0
  test: ^1.14.4
