name: ignite_cli
description: Ignite your projects with flame; a CLI scaffolding tool to create and setup your Flame projects
version: 0.1.0
homepage: https://flame-engine.org/ignite

# Add the bin/ignite.dart script to the scripts pub installs
executables:
  ignite:

environment:
  sdk: '>=2.9.3 <3.0.0'

dependencies:
  args: ^1.6.0
  completion: ^0.2.2
  process_run: ^0.11.2
  prompts: ^1.3.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
